FROM golang:1.25.6-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o myapp ./cmd/api/main.go


FROM alpine:latest

WORKDIR /

COPY --from=builder /app/myapp /myapp
COPY --from=builder /app/database /database

EXPOSE 8080
ENTRYPOINT ["/myapp"]